### ISSUE TITLE
bug: Attack시 기존 단어와 위치가 겹치는 문제

### ISSUE THREAD

**Issue by ChangHoon-Sung** [KMUCS23-RUST-A/raingame-rs#11]
새로운 단어 생성은 `game.spawn_word()`의 호출로 이루어진다.

그런데 공격은 단어 생성의 딜레이를 받지 않다보니, 이미 생성된 단어와 X좌표가 유사한 경우 글자가 가려지는 문제가 있다.

새로 생성하려는 단어가 가장 마지막으로 생성한 단어로부터 최소 N칸 이상 차이가 나도록 생성하도록 수정해야 한다.

**Comment by nanana3679** [comment]
최근 생성한 단어로부터 1칸 이상 떨어져 생성되도록 수정했습니다.

**Comment by ChangHoon-Sung** [comment]
Commit(https://github.com/KMUCS23-RUST-A/raingame-rs/commit/ed66f83400dc6ddb5b04437bb5ba21b5e627cf8a) is  related with this issue
