### ISSUE TITLE
feat: Export game result

### ISSUE THREAD

**Issue by ChangHoon-Sung** [KMUCS23-RUST-A/raingame-rs#20]
게임의 결과를 파일로 저장하는 기능을 추가한다.

위 저장 기능은 Client에서 게임 쓰레드의 Teardown 단계에 수행되어야 한다.

파일의 저장 방식은 아래와 같이 구현한다.
1. 클라이언트 바이너리 파일이 위치한 디렉토리에 `log` 폴더 생성
2. 해당 폴더 안에 `YYYY-MM-DD_HH-MM-SS.log` 형식으로 게임 결과 파일 생성
3. 파일 내용에는 게임 점수 단순 기록

**Comment by nanana3679** [comment]
클라이언트를 식별할 수 있는 정보를 기록하면 용준님이 말씀하셨던 진 플레이어를 킥하는 기능을 만들 수도 있을 것 같은데, 시간이 없으니 일단 최소한의 구성으로 구현해야 할 것 같아요.
