### ISSUE TITLE
단어 입력에 따른 상태 정의

### ISSUE THREAD

**Issue by ChangHoon-Sung** [KMUCS23-RUST-A/raingame-rs#6]
Game.update(input)에서 반환하는 현재 단어에 대한 상태를 정의한다.

가능한 상태
- 아직 단어가 완성되지 않음
- 일반 단어 완성
- 공격 단어 완성
- 단어 틀렸음

**Comment by nanana3679** [comment]
game_state를 get 함수로 받아오는 코드를 feat/client 브랜치로 작성하였는데, 만들다보니 논의했던 거랑 조금 다른 형태가 된 것 같습니다.

**Comment by ChangHoon-Sung** [comment]
@nanana3679 어떤 식으로 달라졌는지 대략적으로 알려주시겠어요?
여기에 적기에 내용이 많으면 PR을 새로 만들어주시고, PR에 변경된 부분 혹은 제안을 작성해주세요!
